### ISSUE TITLE
断点续传存在bug

### ISSUE THREAD

**Issue by vinllen** [alibaba/NimoShake#1]
checkpoint的存储跟数据是分离的，checkpoint定期存储，一旦挂掉重启会从上一个checkpoint开始拉取，由于checkpoint本身不是随数据实时写入，会存在数据重复拉取。而写入由于没有mongodb的_id，导致一条数据重复拉取消费后，在目的端就有多条数据了。
例如：源dynamodb
![image](https://user-images.githubusercontent.com/6987398/67928744-be047300-fbf6-11e9-8471-fc3c91a0ac4a.png)
目的mongodb
![image](https://user-images.githubusercontent.com/6987398/67928770-c5c41780-fbf6-11e9-94df-8c8d9ea771cf.png)
解决的办法有几种：
1. 写入的batch数据随checkpoint一起封装成一个事务，不过这样写就会存在一定的放大，但是考虑到batch以后还是可以接受的。缺点是老版本不支持事务，那么这个就没办法了，不过目前随着4.0的推进越来越多，这个是可以接受的。
2. 另外搞一个主键id，根据用户的primary key写入mongodb当做主键id，写入冲突再去解冲突。但不足之处是用户本来可能就没有唯一的key，其二，修改主键_id对mongodb本身来说不太合适。

**Comment by lqjack** [comment]
add the patch

**Comment by vinllen** [comment]
对于primary key，如果只存在partition key，则是唯一键，如果存在partition key+sort key，则联合唯一键。
这个默认目的端建索引即可，为了保证幂等性：

- 对于Insert操作，冲突则改为update
- 对于update操作，报错不存在则忽略；冲突也忽略。
- 对于delete操作，报错不存在则忽略。

**Comment by vinllen** [comment]
1.0.2版本已经进行调整，同步会同步partition key+sort key，根据这个构建唯一键保证幂等性。数据重复回放根据上述策略保证幂等性。
