### ISSUE TITLE
同步时DDL 支持问题

### ISSUE THREAD

**Issue by qingw1983** [alibaba/NimoShake#2]
请问在增量或全量同步的时候，从文档上看是不支持原来的表的DDL(比如删表，建表，建索引等) 操作，这个意思是指源表上的DDL 操作不会同步到目标表吗？这个后续会支持吗？现在有什么其他的解决方案呢？

**Comment by vinllen** [comment]
增量的streams是基于表级别来的，删表、建表、重命名表肯定是不支持，因为这本来就需要源端开启stream功能，没有动态去监听这个过程。
建索引也是一次性在全量结束后同步的，没有增量同步，本身也受限于dynamodb的stream，没有吐出这个变更消息。
后续暂时没有计划进行支持，实现比较复杂。
解决方式是同步过程需要避免上述操作。
